### ISSUE TITLE
No device?

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABCaptureManager#1]
what am I doing wrong? no errors from Xcode

no device
*** ___ZN11XPCEndPoint20sendMessageWithReplyEP10XPCMessagePS1_P16dispatch_queue_s_block_invoke[225]: XPC event error 'connection invalid'
*** waitForReply[294]: Error completing transaction (connection invalid)
*** completeTransactionAndProcessReply[497]: Error waiting for transaction reply
*** CreateNewClient[26]: Couldnt connect to XPC service
*** ___ZN11XPCEndPoint20sendMessageWithReplyEP10XPCMessagePS1_P16dispatch_queue_s_block_invoke[225]: XPC event error 'connection invalid'
*** waitForReply[294]: Error completing transaction (connection invalid)
*** completeTransactionAndProcessReply[497]: Error waiting for transaction reply
*** CreateNewClient[26]: Couldnt connect to XPC service

**Comment by MyCometG3** [comment]
Not reproducible. Did you installed the driver first?
- I have tested with latest Driver and Xcode 10.1. 

Please verify following:
- Install Blackmagic_Desktop_Video_10.11.4.dmg first
- copy DLABridging.framework, or build DLABridging
- copy DLABCaptureManager, or build DLABCaptureManager
- Build your app project

**Comment by kcwvc52** [comment]
all updated, still same error can you send me that simp[le project to see if I can figure out what I am doing wrong. thanks

**Comment by MyCometG3** [comment]
It shows XPC related errors.

- Verify System Settings -> Security & Privacy and allow extension to work
Blackmagic Desktop video installs system extension - which can be blocked by gatekeeper (MacOS 10.14~).

- Try rebuild both DLABxxxx.frameworks using your developer ID
If your problem is caused by sandbox issue, this could be solution.

**Comment by MyCometG3** [comment]
This is simple test code - both start/stop capture, and monitor device hot insert/remove.

    import Cocoa
    import DLABridging
    import DLABCaptureManager
    
    @NSApplicationMain
    class AppDelegate: NSObject, NSApplicationDelegate, DLABBrowserDelegate {
        var manager :DLABCaptureManager? = nil
        func applicationDidFinishLaunching(_ aNotification: Notification) {
            dumpDeviceList(inputVideoSettings: false, outputVideoSettings: false)
        }
        private func dumpDeviceList(inputVideoSettings input :Bool, outputVideoSettings output :Bool) {
            if manager == nil {
                manager = DLABCaptureManager()
            }
            if let manager = manager {
                #if true
                    print("##### devices #####")
                    let deviceList = manager.deviceList()
                    if let deviceList = deviceList {
                        for device in deviceList {
                            let deviceInfo = manager.deviceInfo(device: device)
                            print(deviceInfo)
                            
                            dumpVideoSettingList(device, input, output)
                        }
                    }
                    print("##### done #####")
                #else
                    var browser :DLABBrowser? = DLABBrowser()
                    if let browser = browser {
                        browser.delegate = self
                        print("start!")
                        browser.start()
                        print(">>running: \(browser.isRunning)")
                        DispatchQueue.main.asyncAfter(deadline: .now() + 10, execute: { () in
                            print("stop!")
                            browser.stop()
                            print(">>running: \(browser.isRunning)")
                        })
                    }
                    browser = nil
                #endif
            }
            manager = nil
        }
        
        private func dumpVideoSettingList(_ device :DLABDevice, _ input :Bool, _ output :Bool) {
            if input, let manager = manager {
                print("##### input #####")
                let inputList = manager.inputVideoSettingList(device: device)
                if let inputList = inputList {
                    for setting in inputList {
                        let settingInfo = manager.videoSettingInfo(setting: setting)
                        print(settingInfo)
                    }
                }
            }
            
            if output, let manager = manager {
                print("##### output #####")
                let outputList = manager.outputVideoSettingList(device: device)
                if let outputList = outputList {
                    for setting in outputList {
                        let settingInfo = manager.videoSettingInfo(setting: setting)
                        print(settingInfo)
                    }
                }
            }
        }
        
        func didAdd(_ device: DLABDevice, of sender: DLABBrowser) {
            print ("didAdd")
        }
        
        func didRemove(_ device: DLABDevice, of sender: DLABBrowser) {
            print ("didRemove")
        }
    }

**Comment by igomez084** [comment]
Hello, I am having exactly the same problem. I can record with Blackmagic Media Express, I can see the preview with Capture Preview of Blackmagic DeckLink SDK, but no device is detected with DLABCaptureManager.

The message I am getting:
`*** waitForReply[294]: Error completing transaction (connection invalid)
*** completeTransactionAndProcessReply[497]: Error waiting for transaction reply
*** CreateNewClient[26]: Couldnt connect to XPC service
*** ___ZN11XPCEndPoint20sendMessageWithReplyEP10XPCMessagePS1_P16dispatch_queue_s_block_invoke[225]: XPC event error 'connection invalid'
*** waitForReply[294]: Error completing transaction (connection invalid)
*** completeTransactionAndProcessReply[497]: Error waiting for transaction reply
*** CreateNewClient[26]: Couldnt connect to XPC service`

What do you think is the problem?

Thank you in advance for the help and also thanks you for your work.
