### ISSUE TITLE
getting this issue any guesses why?

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABCaptureManager#10]
/Users/minireplay/Desktop/container decklink try/container decklink try/cam6vc.swift:10:8 Could not find module 'DLABCaptureManager' for target 'arm64-apple-macos'; found: x86_64, x86_64-apple-macos, at: /Users/minireplay/Desktop/container decklink try/DLABCaptureManager.framework/Modules/DLABCaptureManager.swiftmodule

**Comment by MyCometG3** [comment]
Too little information provided - It is difficult to figure out the root cause.

I recommend you to try swift package instead of framework
see: https://github.com/MyCometG3/DLAB
