### ISSUE TITLE
selecting device.

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABCaptureManager#2]
anyway to select a device other than findfirstdevice()? what if you have several Blackmagic devices plugged in. am I missing something?

**Comment by MyCometG3** [comment]
Do you mean deviceList()?

                print("##### devices #####")
                let deviceList = manager.deviceList()
                if let deviceList = deviceList {
                    for device in deviceList {
                        let deviceInfo = manager.deviceInfo(device: device)
                        print(deviceInfo)
                        
                        dumpVideoSettingList(device, input, output)
                    }
                }
                print("##### done #####")

**Comment by kcwvc52** [comment]
thanks I got where I needed from there. so is it possible to start 2 capture session in the same project simultaneously?

**Comment by MyCometG3** [comment]
Unfortunately, you can process only one capture device, one capture session at a time.

**Comment by kcwvc52** [comment]
Dang, that was a big waste of time. Know any framework that works with swift that will?
