### ISSUE TITLE
Problem detecting device

### ISSUE THREAD

**Issue by igomez084** [MyCometG3/DLABCaptureManager#3]
Hello, I am having exactly the same problem as one of the closed issues, but I could not find any solution there, so I opened a new one. I hope that is ok.

I can record with Blackmagic Media Express, I can see the preview with Capture Preview of Blackmagic DeckLink SDK, but no device is detected with DLABCaptureManager.

The message I am getting:
`*** waitForReply[294]: Error completing transaction (connection invalid) *** completeTransactionAndProcessReply[497]: Error waiting for transaction reply *** CreateNewClient[26]: Couldnt connect to XPC service *** ___ZN11XPCEndPoint20sendMessageWithReplyEP10XPCMessagePS1_P16dispatch_queue_s_block_invoke[225]: XPC event error 'connection invalid' *** waitForReply[294]: Error completing transaction (connection invalid) *** completeTransactionAndProcessReply[497]: Error waiting for transaction reply *** CreateNewClient[26]: Couldnt connect to XPC service`

What do you think is the problem?

Thank you in advance for the help and also thanks you for your work.

**Comment by MyCometG3** [comment]
I am still unable to reproduce this issue. Please confirm the code sign first.

Did you perform code-sign on both DLABridging.framework and DLABCaptureManager.framework "with your DeveloperID"?
For reference, see [Technical Note TN2206](https://developer.apple.com/library/archive/technotes/tn2206/_index.html).

**Comment by igomez084** [comment]
Yes, I have signed with my DeveloperID.

I have been testing with a Blackmagic Mini Recorder. As I mentioned, Capture Preview of Blackmagic DeckLink SDK works perfectly.

Is there something else I could try?

Thank you in advance.

**Comment by MyCometG3** [comment]
Try DLABridging.framework instead of this wrapper framework.
Verify the deviceList contains devices.
If no device is detected, I think simple c++ sample code wouldn't work.

```
1. Find DLABDevice using DLABBrowser

import Cocoa
import DLABridging
var device :DLABDevice? = nil

do {
  let browser = DLABBrowser()
  _ = browser.registerDevicesForInput()
  let deviceList = browser.allDevices
  device = deviceList.first!
}
```
//
NOTE: Above code simply trigger:
```
IDeckLinkIterator* iterator = CreateDeckLinkIteratorInstance();
```
then create DLABDevice object.
//
https://github.com/MyCometG3/DLABridging/blob/master/Source/DLABBrowser.mm#L236
https://github.com/MyCometG3/DLABridging/blob/master/Source/DLABBrowser.mm#L313
https://github.com/MyCometG3/DLABridging/blob/master/Source/DLABDevice.mm#L28
//

**Comment by igomez084** [comment]
I've tried to check if the device is detected, but the deviceList array is empty. Nothing is detected.

**Comment by MyCometG3** [comment]
Do you use sandboxing your app?
If yes, you may require com.apple.security.temporary-exception.mach-lookup.global-name with DeckLinkHardwareXPCService.

Please refer to Blackmagic DeckLink SDK pdf, P.19, "2.2. Sandboxing support on macOS".

**Comment by igomez084** [comment]
I hope this could be a solution. I will let you know if it works by then end of this week (when I will have chance to test it again). Thank you very much for your time and work.

**Comment by igomez084** [comment]
Fixed. The problem was that App Sandbox was activated. Thank you
