### ISSUE TITLE
cannot receive video input from computer

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABCaptureManager#4]
it works fine in Blackmagic media express but when I try to get the signal with the manager/bridging it doesn't work?

**Comment by MyCometG3** [comment]
Hi,
please let me know about:
1) what device do you use? 
2) do you use sandboxed app?

**Comment by kcwvc52** [comment]
1. decklink mini recorder,(I also have decklink duo, and ultra studio) I have it working with video cameras. The signal from a macbook pro isn't working even though it shows up just fine in Blackmagic media express. 

2. sandboxing is set to off in Xcode

**Comment by MyCometG3** [comment]
1) Please give me simple code snippet that you use to verify malfunction.
2) Does DLABBrowser detect your device or not?
3) If yes, what output from device.deviceInfo is available?

**Comment by kcwvc52** [comment]
I'm way past what you are asking. I'm not outputting anything. I don't think you get what I'm saying. I am using one computer's hdmi out(usbc-hdmi) and running into a Blackmagic capture device on another computer. the Blackmagic devices in the software I have written(with the framework) are receiving camera signal perfectly, but when I try to receive a signal from the other computers hdmi port, I get nothing. even though it works in media express.

**Comment by MyCometG3** [comment]
Hmm, basically I am not sure what you met though, possible scenario could be:
- Maybe EDID emulator device could help.
- Current DLAB* frameworks do not support EDID related APIs from SDK 11.x
