### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABCaptureManager#8]
getting this error. any suggestions? first time trying to update things for an m1

![Screen Shot 2022-11-23 at 9 08 42 AM](https://user-images.githubusercontent.com/46359894/203581130-3a43655e-13fd-4a08-8601-d9e46bbf932c.png)

**Comment by MyCometG3** [comment]
CMTimebaseCreateWithSourceClock() is a part of CoreMedia, which is imported in AVFoundation.

**Comment by kcwvc52** [comment]
I understand that but why would there be an error? framework is
obviously included?

**Comment by MyCometG3** [comment]
Hey You should not embed any email address in public space. Use Github Interface always.

I guess it is issue in your project target definition.
It may not include AVFoundation in Xcode TARGET General Frameworks, Libraries, and Embedded Contents.
Or target MINIMUM DEPLOYMENTS configuration error.
